drop view damage_assessment_view;


create VIEW damage_assessment_view as
SELECT da."REF" as damage_assessment_ref,
       da."DATE" as damage_assessment_date,
       da."CreationDateTime" as damage_assessment_creation_date_time,
       da."SurveyDate" as damage_assessment_survey_date,
       da."Comments" as damage_assessment_comments,
       da."Address" as damage_assessment_address,
       da."BuildingName" as damage_assessment_building_name,
       da."FloorsNumber" as damage_assessment_floors_number,
       case
           WHEN da."GeoLocationLatitude" like '33.%' THEN da."GeoLocationLatitude"
           ELSE '0'
       END as damage_assessment_geo_location_latitude,
       case
           WHEN da."GeoLocationLongitude" like '35.%' THEN da."GeoLocationLongitude"
           ELSE '0'
       end as damage_assessment_geo_location_longitude,
       da."ExternalDamageStoneArea" as damage_assessment_external_damage_stone_area,
       da."ExternalDamageConcreteArea" as damage_assessment_external_damage_concrete_area,
       da."ExternalDamageInforcedConcreteArea" as damage_assessment_external_damage_enforced_concrete_area,
       da."BarrierDamageArea" as damage_assessment_barrier_damage_area,
       da."WallDamageArea" as damage_assessment_wall_damage_area,
       da."PaintDamageArea" as damage_assessment_paint_damage_area,
       da."FlooringDamageArea" as damage_assessment_flooring_damage_area,
       da."CeilingDamageArea" as damage_assessment_ceiling_damage_area,
       da."IronDamageWeight" as damage_assessment_iron_damage_weight,
       da."GlassDamageArea" as damage_assessment_glass_damage_area,
       da."AluminumRepairableArea" as damage_assessment_aluminum_repairable_area,
       da."AluminumUnRepairableArea" as damage_assessment_aluminum_unrepair_area,
       da."WoodDamageArea" as damage_assessment_wood_damage_area,
       da."WoodDamagePiece" as damage_assessment_wood_damage_piece,
       da."CurtainDamageArea" as damage_assessment_curtain_damage_area,
       da."LightingDamageBulbs" as damage_assessment_lighting_damage_bulbs,
       da."LightingDamageNeonBulbs" as damage_assessment_lighting_damage_neon_bulbs,
       da."LightingDamageLEDBulbs" as damage_assessment_lighting_damage_led_bulbs,
       da."LightingDamageChandelier" as damage_assessment_lighting_damage_chandelier,
       da."LightingDamageCeiling" as damage_assessment_lighting_damage_ceiling,
       da."LightingDamageOther" as damage_assessment_lighting_damage_other,
       da."SanitaryDamageFaucet" as damage_assessment_sanitary_damage_faucet,
       da."SanitaryDamageSink" as damage_assessment_sanitary_damage_sink,
       da."SanitaryDamageToilet" as damage_assessment_sanitary_damage_toilet,
       da."SanitaryDamageOther" as damage_assessment_sanitary_damage_other,
       da."ElectricityDamageCables" as damage_assessment_electricity_damage_cables,
       da."ElectricityDamageSockets" as damage_assessment_electricity_damage_sockets,
       da."AirConditionerDamageUnits" as damage_assessment_air_conditioner_damage_units,
       da."AirConditionerRepairableParts" as damage_assessment_air_conditioner_repairable_parts,
       da."FurnitureDamageTables" as damage_assessment_furniture_damage_tables,
       da."FurnitureDamageOffice" as damage_assessment_furniture_damage_office,
       da."FurnitureDamageChair" as damage_assessment_furniture_damage_chair,
       da."FurnitureDamageCouch" as damage_assessment_furniture_damage_couch,
       da."FurnitureDamageShelf" as damage_assessment_lighting_damage_shelf,
       da."FurnitureDamageCloset" as damage_assessment_furniture_damage_closet,
       da."FurnitureDamageOther" as damage_assessment_furniture_damage_other,
       da."MachineryDamageComputer" as damage_assessment_machinery_damage_computer,
       da."MachineryDamageLaptop" as damage_assessment_machinery_damage_laptop,
       da."MachineryDamageOther" as damage_assessment_machinery_damage_other,
       da."StorageUnitNumber" as damage_assessment_storage_unit_number,
       da."PaintingCarpetNumber" as damage_assessment_painting_carpet_number,
       da."PaintingCarpetOther" as damage_assessment_painting_carpet_other,
       da."ArchiveNumber" as damage_assessment_archive_number,
       da."ArchiveDamageOther" as damage_assessment_archive_damage_other,
       da."DistanceToExplosionCenter" as damage_assessment_distance_to_explosion_center,
       da."CementDamageArea" as damage_assessment_cement_damage_area,
       da."PaintOilDamageArea" as damage_assessment_paint_oil_damage_area,
       da."FlooringMosaicArea" as damage_assessment_flooring_mosaic_area,
       da."FlooringCeramicArea" as damage_assessment_flooring_ceramic_area,
       da."FlooringMarbleArea" as damage_assessment_flooring_marble_area,
       da."StairsMosaicLength" as damage_assessment_stair_mosaic_length,
       da."StairsMarbleLength" as damage_assessment_stairs_marble_length,
       da."WoodSwedishDamageArea" as damage_assessment_wood_swedish_damage_area,
       da."WoodMahoganyDamageArea" as damage_assessment_wood_mahogany_damage_area,
       da."SanitaryDamageWatertank" as damage_assessment_sanitary_damage_water_tank,
       da."KitchenSinkLength" as damage_assessment_kitchen_sink_length,
       da."KitchenCabinetsLength" as damage_assessment_kitchen_cabinets_length,
       da."VehiclesUnrepairableCar" as damage_assessment_vehicle_unrepairable_car,
       da."VehiclesUnrepairableMiniVan" as damage_assessment_vehicle_unrepairable_mini_van,
       da."VehiclesUnrepairableTruck" as damage_assessment_vehicle_unrepairable_truck,
       da."VehiclesUnrepairableOther" as damage_assessment_vehicle_unrepairable_other,
       da."VehiclesRepairableCar" as damage_assessment_vehicle_repairable_car,
       da."VehiclesRepairableMiniVan" as damage_assessment_vehicle_repairable_mini_van,
       da."VehiclesRepairableTruck" as damage_assessment_vehicle_repairable_truck,
       da."VehiclesRepairableOther" as damage_assessment_vehicle_repairable_other,
       da."ElectronicDeviceTV" as damage_assessment_electronic_device_tv,
       da."ElectronicDeviceScreen" as damage_assessment_electronic_device_screen,
       da."ElectronicDevicePhone" as damage_assessment_electronic_device_phone,
       da."ElectronicDevicePhotoCopy" as damage_assessment_electronic_device_photo_copy,
       da."ElectronicDeviceScanner" as damage_assessment_electronic_device_scanner,
       da."ElectronicDeviceCamera" as damage_assessment_electronic_device_camera,
       da."ElectronicDeviceOther" as damage_assessment_electronic_device_other,
       da."PAName" as damage_assessment_pa_name,
       da."SurveyedFloorsNumber" as damage_assessment_survey_floor_number,
       da."WallDamageConcrete" as damage_assessment_wall_damage_concrete,
       da."WallDamageInforcedConcrete" as damage_assessment_wall_damage_enforced_concrete,
       da."WallDamageStoneCladding" as damage_assessment_wall_damage_stone_cladding,
       da."WallDamageSandstoneCladding" as damage_assessment_wall_damage_sandstone_cladding,
       da."WallDamageMarbleCladding" as damage_assessment_wall_damage_marble_cladding,
       da."WallDamageMosaicCladding" as damage_assessment_wall_damage_mosaic_cladding,
       da."WallCladdingPorclainCladding" as damage_assessment_wall_damage_porcelain_concrete,
       da."WallDamageOther" as damage_assessment_wall_damage_other,
       da."BrickDamageArea" as damage_assessment_brick_damage_area,
       da."FlooringDamageOther" as damage_assessment_flooring_damage_other,
       da."StairStoneTileLength" as damage_assessment_stair_stone_tile_length,
       da."StairDamageOther" as damage_assessment_stair_damage_other,
       da."SanitaryDamageDrainingPipe" as damage_assessment_sanitary_damage_draining_pipe,
       da."SanitaryDamagePump" as damage_assessment_sanitary_damage_pump,
       da."AirConditionerDamage9000BTU" as damage_assessment_air_conditioner_damage_9000_btu,
       da."AirConditionerDamage12000BTU" as damage_assessment_air_conditioner_damage_12000_btu,
       da."AirConditionerDamage18000BTU" as damage_assessment_air_conditioner_damage_18000_btu,
       da."AirConditionerDamage24000BTU" as damage_assessment_air_conditioner_damage_24000_btu,
       da."HeatingDevicesDamagedUnits" as damage_assessment_heating_device_damaged_units,
       da."HeatingDevicesRepairableParts" as damage_assessment_heating_device_repairable_parts,
       da."WaterHeaterDamagedUnits" as damage_assessment_water_heater_damage_units,
       da."WaterHeaterRepairableParts" as damage_assessment_water_heater_repairable_parts,
       da."ElectricalGeneratorDamagedUnits" as damage_assessment_electrical_generator_damage_units,
       da."ElectricalGeneratorRepairableParts" as damage_assessment_electrical_generator_repairable_parts,
       da."DieselTankDamagedUnits" as damage_assessment_diesel_tank_damages_units,
       da."DieselTankRepairableParts" as damage_assessment_diesel_tank_repairable_parts,
       da."FireAlarmDamagedUntis" as damage_assessment_fire_alarm_damage_units,
       da."FireAlarmRepairableParts" as damage_assessment_fire_alarm_repairable_parts,
       da."WoodPlyArea" as damage_assessment_wood_ply_area,
       da."WoodDamageOther" as damage_assessment_wood_damage_other,
       da."KitchenDamageOther" as damage_assessment_kitchen_damage_other,
       da."FurnitureDamageTableClassA" as damage_assessment_furniture_damage_table_class_a,
       da."FurnitureDamageTableClassB" as damage_assessment_furniture_damage_table_class_b,
       da."FurnitureDamageTableClassC" as damage_assessment_furniture_damage_table_class_c,
       da."FurnitureDamageChairClassA" as damage_assessment_furniture_damage_chair_class_a,
       da."FurnitureDamageChairClassB" as damage_assessment_furniture_damage_chair_class_b,
       da."FurnitureDamageChairClassC" as damage_assessment_furniture_damage_chair_class_c,
       da."FurnitureDamageMobileChairClassA" as damage_assessment_furniture_damage_mobile_chair_class_a,
       da."FurnitureDamageMobileChairClassB" as damage_assessment_furniture_damage_mobile_chair_class_b,
       da."FurnitureDamageMobileChairClassC" as damage_assessment_furniture_damage_mobile_chair_class_c,
       da."FurnitureDamageCouchClassA" as damage_assessment_furniture_damage_couch_class_a,
       da."FurnitureDamageCouchClassB" as damage_assessment_furniture_damage_couch_class_b,
       da."FurnitureDamageCouchClassC" as damage_assessment_furniture_damage_couch_class_c,
       da."FurnitureDamageClosetClassA" as damage_assessment_furniture_damage_closet_class_a,
       da."FurnitureDamageClosetClassB" as damage_assessment_furniture_damage_closet_class_b,
       da."FurnitureDamageClosetClassC" as damage_assessment_furniture_damage_closet_class_c,
       da."FurnitureDamageBookcaseClassA" as damage_assessment_furniture_damage_bookcase_class_a,
       da."FurnitureDamageBookcaseClassB" as damage_assessment_furniture_damage_bookcase_class_b,
       da."FurnitureDamageBookcaseClassC" as damage_assessment_furniture_damage_bookcase_class_c,
       da."FurnitureDamageShelfClassA" as damage_assessment_furniture_damage_shelf_class_a,
       da."FurnitureDamageShelfClassB" as damage_assessment_furniture_damage_shelf_class_b,
       da."FurnitureDamageShelfClassC" as damage_assessment_furniture_damage_shelf_class_c,
       da."FurnitureDamageSaplingClassA" as damage_assessment_furniture_damage_sapling_class_a,
       da."FurnitureDamageSaplingClassB" as damage_assessment_furniture_damage_sapling_class_b,
       da."FurnitureDamageSaplingClassC" as damage_assessment_furniture_damage_sapling_class_c,
       da."FurnitureDamageOtherClassA" as damage_assessment_furniture_damage_other_class_a,
       da."FurnitureDamageOtherClassB" as damage_assessment_furniture_damage_other_class_b,
       da."FurnitureDamageOtherClassC" as damage_assessment_furniture_damage_other_class_c,
       da."DamageAssessment_REF" as damage_assessment_self_ref,
       da."WaterHeaterRepairPercent" as damage_assessment_water_heater_repair_percent,
       da."SanitaryDamageSewagePipe" as damage_assessment_sanitary_damage_sewage_pipe,
       da."VehicleRepairPercentage" as damage_assessment_vehicle_repair_percentage,
       da."ElectronicDeviceTV70" as damage_assessment_electronic_device_tv_70,
       da."ElectronicDeviceTV40" as damage_assessment_electronic_device_tv_40,
       da."ElectronicDeviceTV30" as damage_assessment_electronic_device_tv_30,
       da."CarpetOtherDamage" as damage_assessment_carpet_other_damage,
       da."ParquetNumber" as damage_assessment_parquet_number,
       da."MouqetteNumber" as damage_assessment_moquette_number,
       da."CarpetsNumber" as damage_assessment_carpets_number,
       da."ValuablePaintingNumber" as damage_assessment_valuable_painting_number,
       da."FireAlarmRepairPercent" as damage_assessment_fire_alarm_repair_percent,
       da."NormalPaintingNumber" as damage_assessment_normal_painting_number,
       da."DieselTankRepairPercent" as damage_assessment_diesel_tank_repair_percent,
       da."ElectricalGeneratorRepairPercent" as damage_assessment_electrical_generator_repair_percent,
       da."HeatingDeviceRepairPercent" as damage_assessment_heating_device_repair_percent,
       da."AirConditionerRepairPercent" as damage_assessment_air_conditioner_repair_percent,
       da."CurtainDamageMetal" as damage_assessment_curtain_damage_metal,
       da."CurtainDamageFabric" as damage_assessment_curtain_damage_fabric,
       da."WoodDamagePercentage" as damage_assessment_wood_damage_percentage,
       da."GlassDamageDoubleVitrage" as damage_assessment_glass_damage_double_glazing,
       da."GlassDamageColoredGlass6mm" as damage_assessment_glass_damage_colored_glass_6mm,
       da."GlassDamageColoredGlass4mm" as damage_assessment_glass_damage_colored_glass_4mm,
       da."GlassDamageColoredGlass2mm" as damage_assessment_glass_damage_colored_glass_2mm,
       da."GlassDamageWhiteGlass6mm" as damage_assessment_glass_damage_white_glass_6mm,
       da."GlassDamageWhiteGlass4mm" as damage_assessment_glass_damage_white_glass_4mm,
       da."GlassDamageWhiteGlass2mm" as damage_assessment_glass_damage_white_glass_2mm,
       da."PaintDamageBase" as damage_assessment_paint_damage_base,
       da."PaintDamagePaint" as damage_assessment_paint_damage_paint,
       da."PaintDamagePaste" as damage_assessment_paint_damage_past,
       da."PartitionDamageWood" as damage_assessment_partition_damaged_wood,
       da."PartitionDamageOther" as damage_assessment_partition_damaged_other,
       da."PartitionDamageCement" as damage_assessment_partition_damaged_cement,
       da."PartitionDamageGlass" as damage_assessment_partition_damaged_glass,
       da."PartitionDamageGypsum" as damage_assessment_partition_damaged_gypsum,
       da."ExternalCladdingOther" as damage_assessment_external_cladding_other,
       da."ExternalCladdingSantex" as damage_assessment_external_cladding_sandtex,
       da."ExternalCladdingAluminum" as damage_assessment_external_cladding_aluminum,
       da."ExternalCladdingMarble" as damage_assessment_external_cladding_marble,
       da."ExternalCladdingRockstone" as damage_assessment_external_cladding_rock_stone,
       fad."NAME" as fire_alarm_damage_evaluation,
       egd."NAME" as electrical_generator_damage_evaluation,
       whd."NAME" as water_heater_damage_evaluation,
       hdd."NAME" as heating_device_damage_evaluation,
       bd."NAME" as brick_damage_evaluation,
       vd."NAME" as vehicles_damage_evaluation,
       edd."NAME" as electronic_device_damage_evaluation,
       kd."NAME" as kitchen_damage_evaluation,
       st."NAME" as stair_damage_evaluation,
       cd."NAME" as cement_damage_evaluation,
       evd."NAME" as elevator_damage_evaluation,
       tbd."NAME" as total_building_damage_evaluation,
       ad."NAME" as archive_damage_evaluation,
       pcd."NAME" as paint_carpet_damage_evaluation,
       sud."NAME" as storage_unit_damage_evaluation,
       bad."NAME" as barrier_damage_evaluation,
       wall."NAME" as wall_damage_evaluation,
       paint."NAME" as paint_damage_evaluation,
       flooring."NAME" as flooring_damage_evaluation,
       cei."NAME" as ceiling_damage_evaluation,
       iron."NAME" as iron_damage_evaluation,
       glass."NAME" as glass_damage_evaluation,
       ald."NAME" as aluminum_damage_evaluation,
       wood."NAME" as wood_damage_evaluation,
       curtain."NAME" as curtain_damage_evaluation,
       lighting."NAME" as lighting_damage_evaluation,
       sanitary."NAME" as sanitary_damage_evaluation,
       electricity."NAME" as electricity_damage_evaluation,
       ac."NAME" as air_conditioner_damage_evaluation,
       furniture."NAME" as furniture_damage_evaluation,
       machinery."NAME" as machinery_damage_evaluation,
       ed."NAME" as external_damage_evaluation,
       ecd."NAME" as external_cladding_damage_evaluation,
       pd."NAME" as partition_damage_evaluation,
       fad."Type" as fire_alarm_damage_evaluation_type,
       egd."Type" as electrical_generator_damage_evaluation_type,
       whd."Type" as water_heater_damage_evaluation_type,
       hdd."Type" as heating_device_damage_evaluation_type,
       bd."Type" as brick_damage_evaluation_type,
       vd."Type" as vehicles_damage_evaluation_type,
       edd."Type" as electronic_device_damage_evaluation_type,
       kd."Type" as kitchen_damage_evaluation_type,
       st."Type" as stair_damage_evaluation_type,
       cd."Type" as cement_damage_evaluation_type,
       evd."Type" as elevator_damage_evaluation_type,
       tbd."Type" as total_building_damage_evaluation_type,
       ad."Type" as archive_damage_evaluation_type,
       pcd."Type" as paint_carpet_damage_evaluation_type,
       sud."Type" as storage_unit_damage_evaluation_type,
       bad."Type" as barrier_damage_evaluation_type,
       wall."Type" as wall_damage_evaluation_type,
       paint."Type" as paint_damage_evaluation_type,
       flooring."Type" as flooring_damage_evaluation_type,
       cei."Type" as ceiling_damage_evaluation_type,
       iron."Type" as iron_damage_evaluation_type,
       glass."Type" as glass_damage_evaluation_type,
       ald."Type" as aluminum_damage_evaluation_type,
       wood."Type" as wood_damage_evaluation_type,
       curtain."Type" as curtain_damage_evaluation_type,
       lighting."Type" as lighting_damage_evaluation_type,
       sanitary."Type" as sanitary_damage_evaluation_type,
       electricity."Type" as electricity_damage_evaluation_type,
       ac."Type" as air_conditioner_damage_evaluation_type,
       furniture."Type" as furniture_damage_evaluation_type,
       machinery."Type" as machinery_damage_evaluation_type,
       ed."Type" as external_damage_evaluation_type,
       ecd."Type" as external_cladding_damage_evaluation_type,
       pd."Type" as partition_damage_evaluation_type,
       bo."NAME" as building_owner_ship_name,
       pin."NAME" as public_administration_name,
       u."NAME" as user_name,
       u."FULL_NAME" as user_full_name,
       u."Phone" as user_phone,
       u."FirstName" as user_first_name,
       u."LastName" as user_last_name,
       u."REF" as user_ref,
       grp."NAME" as user_group
from "DamageAssessment" da
left join "BuildingOwnership" bo on bo."REF" = da."BuildingOwnership_REF"
left join "PublicInstitution" pin on pin."REF" = da."PublicAdministration_REF"
left join "FUSER" u ON u."REF" = da."CreationUser_REF"
left join "FGROUP" grp on grp."REF" = u."GRP_REF"
left join "DamageEvaluation" wall on wall."REF" = da."WallDamage_REF"
left join "DamageEvaluation" paint on paint."REF" = da."PaintDamage_REF"
left join "DamageEvaluation" flooring on flooring."REF" = da."FlooringDamage_REF"
left join "DamageEvaluation" cei on cei."REF" = da."CeilingDamage_REF"
left join "DamageEvaluation" iron on iron."REF" = da."IronDamage_REF"
left join "DamageEvaluation" glass on glass."REF" = da."GlassDamage_REF"
left join "DamageEvaluation" ald on ald."REF" = da."AluminumDamage_REF"
left join "DamageEvaluation" wood on wood."REF" = da."WoodDamage_REF"
left join "DamageEvaluation" curtain on curtain."REF" = da."CurtainDamage_REF"
left join "DamageEvaluation" lighting on lighting."REF" = da."LightingDamage_REF"
left join "DamageEvaluation" sanitary on sanitary."REF" = da."SanitaryDamage_REF"
left join "DamageEvaluation" electricity on electricity."REF" = da."ElectricityDamage_REF"
left join "DamageEvaluation" ac on ac."REF" = da."AirConditionerDamage_REF"
left join "DamageEvaluation" furniture on furniture."REF" = da."FurnitureDamage_REF"
left join "DamageEvaluation" machinery on machinery."REF" = da."MachineryDamage_REF"
left join "DamageEvaluation" fad on fad."REF" = da."FireAlarmDamage_REF"
left join "DamageEvaluation" egd on egd."REF" = da."ElectricalGeneratorDamage_REF"
left join "DamageEvaluation" whd on whd."REF" = da."WaterHeaterDamage_REF"
left join "DamageEvaluation" hdd on hdd."REF" = da."HeatingDevicesDamage_REF"
left join "DamageEvaluation" bd on bd."REF" = da."BrickDamage_REF"
left join "DamageEvaluation" ed on ed."REF" = da."ExternalDamage_REF"
left join "DamageEvaluation" vd on vd."REF" = da."VehiclesDamage_REF"
left join "DamageEvaluation" edd on edd."REF" = da."ElectronicDeviceDamage_REF"
left join "DamageEvaluation" kd on kd."REF" = da."KitchenDamage_REF"
left join "DamageEvaluation" st on st."REF" = da."StairDamage_REF"
left join "DamageEvaluation" cd on cd."REF" = da."CementDamage_REF"
left join "DamageEvaluation" evd on evd."REF" = da."ElevatorDamage_REF"
left join "DamageEvaluation" tbd on tbd."REF" = da."TotalBuildingDamage_REF"
left join "DamageEvaluation" ad on ad."REF" = da."ArchiveDamage_REF"
left join "DamageEvaluation" pcd on pcd."REF" = da."PaintingCarpetDamage_REF"
left join "DamageEvaluation" sud on sud."REF" = da."StorageUnitDamage_REF"
left join "DamageEvaluation" bad on bad."REF" = da."BarrierDamage_REF"
left join "DamageEvaluation" ecd on ecd."REF" = da."ExternalCladdingDamage_REF"
left join "DamageEvaluation" pd on pd."REF" = da."PartitionDamage_REF" ;

